"""Add missing user fields

Revision ID: accd3b0e26ba
Revises: 9c95f973b376
Create Date: 2026-02-17 10:45:16.873296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accd3b0e26ba'
down_revision: Union[str, None] = '9c95f973b376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing user fields for password reset and other functionality
    op.add_column('users', sa.Column('reset_token', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('age', sa.String(10), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns if needed
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
