"""Update subscription model: replace plan_id with name field

Revision ID: 3a0f951d1336
Revises: 1372531a5676
Create Date: 2026-01-30 22:48:56.712828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0f951d1336'
down_revision: Union[str, None] = '1372531a5676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add name column as nullable first
    op.add_column('subscriptions', sa.Column('name', sa.String(length=255), nullable=True))
    
    # Update existing records to convert plan_id to name
    op.execute("""
        UPDATE subscriptions 
        SET name = CASE 
            WHEN plan_id = 'basic' THEN 'Basic Plan'
            WHEN plan_id = 'premium' THEN 'Premium Plan'
            WHEN plan_id = 'enterprise' THEN 'Enterprise Plan'
            ELSE COALESCE(plan_id, 'Default Plan')
        END
        WHERE name IS NULL
    """)
    
    # Now make the column not nullable
    op.alter_column('subscriptions', 'name', nullable=False)
    
    # Drop old indexes
    op.drop_index('idx_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan_status', table_name='subscriptions')
    
    # Create new indexes
    op.create_index('idx_subscriptions_name', 'subscriptions', ['name'], unique=False)
    op.create_index('idx_subscriptions_name_status', 'subscriptions', ['name', 'status'], unique=False)
    
    # Drop the old plan_id column
    op.drop_column('subscriptions', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add plan_id column as nullable first
    op.add_column('subscriptions', sa.Column('plan_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    # Update existing records to convert name back to plan_id
    op.execute("""
        UPDATE subscriptions 
        SET plan_id = CASE 
            WHEN name LIKE '%Basic%' THEN 'basic'
            WHEN name LIKE '%Premium%' THEN 'premium'
            WHEN name LIKE '%Enterprise%' THEN 'enterprise'
            ELSE 'basic'
        END
        WHERE plan_id IS NULL
    """)
    
    # Make plan_id not nullable
    op.alter_column('subscriptions', 'plan_id', nullable=False)
    
    # Drop new indexes
    op.drop_index('idx_subscriptions_name_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_name', 'subscriptions')
    
    # Recreate old indexes
    op.create_index('idx_subscriptions_plan_status', 'subscriptions', ['plan_id', 'status'], unique=False)
    op.create_index('idx_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    
    # Drop the name column
    op.drop_column('subscriptions', 'name')
    # ### end Alembic commands ###
