"""Add variant tracking models

Revision ID: 9c95f973b376
Revises: 2026_02_13_retry
Create Date: 2026-02-16 09:09:54.667440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from core.db import GUID

# revision identifiers, used by Alembic.
revision: str = '9c95f973b376'
down_revision: Union[str, None] = '2026_02_13_retry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_points_transactions_account_status'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_account_type'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_created_at'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_loyalty_account_id'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_order_id'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_reason_code'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_status'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_subscription_id'), table_name='points_transactions')
    op.drop_index(op.f('idx_points_transactions_type'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_created_at'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_created_by'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_loyalty_account_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_order_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_subscription_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index(op.f('idx_loyalty_accounts_available_points'), table_name='loyalty_accounts')
    op.drop_index(op.f('idx_loyalty_accounts_status'), table_name='loyalty_accounts')
    op.drop_index(op.f('idx_loyalty_accounts_tier'), table_name='loyalty_accounts')
    op.drop_index(op.f('idx_loyalty_accounts_total_points'), table_name='loyalty_accounts')
    op.drop_index(op.f('idx_loyalty_accounts_user_id'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_created_at'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_created_by'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_id'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_user_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.alter_column('contact_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contact_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contact_messages', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_priority'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_status'), table_name='contact_messages')
    op.drop_column('product_variants', 'max_price')
    op.drop_column('product_variants', 'min_price')
    op.create_index('idx_sub_product_association_variant', 'subscription_product_association', ['product_variant_id'], unique=False)
    op.drop_index(op.f('idx_subscription_products_removed_at'), table_name='subscription_products')
    op.drop_index(op.f('idx_subscription_products_active'), table_name='subscription_products')
    op.create_index('idx_subscription_products_active', 'subscription_products', ['subscription_id', 'product_id'], unique=False, postgresql_where=sa.text('removed_at IS NULL'))
    op.add_column('subscriptions', sa.Column('last_payment_error', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_gateway', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('delivery_type', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('delivery_address_id', GUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('price_at_creation', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('variant_prices_at_creation', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('shipping_amount_at_creation', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('tax_amount_at_creation', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('tax_rate_at_creation', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_variant_prices', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_shipping_amount', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_tax_amount', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_tax_rate', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('subscription_metadata', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_id', GUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_type', sa.String(length=20), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_value', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_code', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_subscriptions_auto_renew'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_billing_cycle'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_cancelled_at'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_name'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_name_status'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_status_billing'), table_name='subscriptions')
    op.create_index('idx_subscriptions_active', 'subscriptions', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_subscriptions_delivery_address', 'subscriptions', ['delivery_address_id'], unique=False)
    op.create_index('idx_subscriptions_status_next_billing', 'subscriptions', ['status', 'next_billing_date'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'promocodes', ['discount_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'addresses', ['delivery_address_id'], ['id'])
    op.drop_column('subscriptions', 'cost_breakdown')
    op.drop_column('subscriptions', 'tax_validated_at')
    op.drop_column('subscriptions', 'tax_rate')
    op.drop_column('subscriptions', 'tax_amount')
    op.drop_column('subscriptions', 'discount_amount')
    op.drop_column('subscriptions', 'price')
    op.drop_column('subscriptions', 'shipping_validated_at')
    op.drop_column('subscriptions', 'total')
    op.drop_column('subscriptions', 'variant_quantities')
    op.drop_column('subscriptions', 'subtotal')
    op.drop_column('subscriptions', 'shipping_cost')
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.add_column('subscriptions', sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('variant_quantities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('shipping_validated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('tax_validated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('cost_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index('idx_subscriptions_status_next_billing', table_name='subscriptions')
    op.drop_index('idx_subscriptions_delivery_address', table_name='subscriptions')
    op.drop_index('idx_subscriptions_active', table_name='subscriptions', postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('idx_subscriptions_status_billing'), 'subscriptions', ['status', 'next_billing_date'], unique=False)
    op.create_index(op.f('idx_subscriptions_name_status'), 'subscriptions', ['name', 'status'], unique=False)
    op.create_index(op.f('idx_subscriptions_name'), 'subscriptions', ['name'], unique=False)
    op.create_index(op.f('idx_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('idx_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('idx_subscriptions_cancelled_at'), 'subscriptions', ['cancelled_at'], unique=False)
    op.create_index(op.f('idx_subscriptions_billing_cycle'), 'subscriptions', ['billing_cycle'], unique=False)
    op.create_index(op.f('idx_subscriptions_auto_renew'), 'subscriptions', ['auto_renew'], unique=False)
    op.drop_column('subscriptions', 'discount_code')
    op.drop_column('subscriptions', 'discount_value')
    op.drop_column('subscriptions', 'discount_type')
    op.drop_column('subscriptions', 'discount_id')
    op.drop_column('subscriptions', 'subscription_metadata')
    op.drop_column('subscriptions', 'current_tax_rate')
    op.drop_column('subscriptions', 'current_tax_amount')
    op.drop_column('subscriptions', 'current_shipping_amount')
    op.drop_column('subscriptions', 'current_variant_prices')
    op.drop_column('subscriptions', 'tax_rate_at_creation')
    op.drop_column('subscriptions', 'tax_amount_at_creation')
    op.drop_column('subscriptions', 'shipping_amount_at_creation')
    op.drop_column('subscriptions', 'variant_prices_at_creation')
    op.drop_column('subscriptions', 'price_at_creation')
    op.drop_column('subscriptions', 'delivery_address_id')
    op.drop_column('subscriptions', 'delivery_type')
    op.drop_column('subscriptions', 'payment_reference')
    op.drop_column('subscriptions', 'payment_gateway')
    op.drop_column('subscriptions', 'last_payment_error')
    op.drop_index('idx_subscription_products_active', table_name='subscription_products', postgresql_where=sa.text('removed_at IS NULL'))
    op.create_index(op.f('idx_subscription_products_active'), 'subscription_products', ['subscription_id', 'removed_at'], unique=False)
    op.create_index(op.f('idx_subscription_products_removed_at'), 'subscription_products', ['removed_at'], unique=False)
    op.drop_index('idx_sub_product_association_variant', table_name='subscription_product_association')
    op.add_column('product_variants', sa.Column('min_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('max_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_contact_messages_status'), 'contact_messages', ['status'], unique=False)
    op.create_index(op.f('ix_contact_messages_priority'), 'contact_messages', ['priority'], unique=False)
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.alter_column('contact_messages', 'resolved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contact_messages', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contact_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('loyalty_accounts',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tier_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('points_earned_lifetime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points_redeemed_lifetime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referrals_made', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_referrals', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tier_benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('loyalty_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('loyalty_accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('loyalty_accounts_pkey'))
    )
    op.create_index(op.f('ix_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=True)
    op.create_index(op.f('ix_loyalty_accounts_id'), 'loyalty_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_created_by'), 'loyalty_accounts', ['created_by'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_created_at'), 'loyalty_accounts', ['created_at'], unique=False)
    op.create_index(op.f('idx_loyalty_accounts_user_id'), 'loyalty_accounts', ['user_id'], unique=False)
    op.create_index(op.f('idx_loyalty_accounts_total_points'), 'loyalty_accounts', ['total_points'], unique=False)
    op.create_index(op.f('idx_loyalty_accounts_tier'), 'loyalty_accounts', ['tier'], unique=False)
    op.create_index(op.f('idx_loyalty_accounts_status'), 'loyalty_accounts', ['status'], unique=False)
    op.create_index(op.f('idx_loyalty_accounts_available_points'), 'loyalty_accounts', ['available_points'], unique=False)
    op.create_table('points_transactions',
    sa.Column('loyalty_account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('points_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('related_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loyalty_account_id'], ['loyalty_accounts.id'], name=op.f('points_transactions_loyalty_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('points_transactions_pkey'))
    )
    op.create_index(op.f('ix_points_transactions_subscription_id'), 'points_transactions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_order_id'), 'points_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_loyalty_account_id'), 'points_transactions', ['loyalty_account_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_id'), 'points_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_points_transactions_created_by'), 'points_transactions', ['created_by'], unique=False)
    op.create_index(op.f('ix_points_transactions_created_at'), 'points_transactions', ['created_at'], unique=False)
    op.create_index(op.f('idx_points_transactions_type'), 'points_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('idx_points_transactions_subscription_id'), 'points_transactions', ['subscription_id'], unique=False)
    op.create_index(op.f('idx_points_transactions_status'), 'points_transactions', ['status'], unique=False)
    op.create_index(op.f('idx_points_transactions_reason_code'), 'points_transactions', ['reason_code'], unique=False)
    op.create_index(op.f('idx_points_transactions_order_id'), 'points_transactions', ['order_id'], unique=False)
    op.create_index(op.f('idx_points_transactions_loyalty_account_id'), 'points_transactions', ['loyalty_account_id'], unique=False)
    op.create_index(op.f('idx_points_transactions_created_at'), 'points_transactions', ['created_at'], unique=False)
    op.create_index(op.f('idx_points_transactions_account_type'), 'points_transactions', ['loyalty_account_id', 'transaction_type'], unique=False)
    op.create_index(op.f('idx_points_transactions_account_status'), 'points_transactions', ['loyalty_account_id', 'status'], unique=False)
    # ### end Alembic commands ###
