"""move_variant_specific_fields_from_product_to_variant

Revision ID: b798a82bfa90
Revises: 3a0f951d1336
Create Date: 2026-02-02 11:34:39.999055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b798a82bfa90'
down_revision: Union[str, None] = '3a0f951d1336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('min_price', sa.Float(), nullable=True))
    op.add_column('product_variants', sa.Column('max_price', sa.Float(), nullable=True))
    op.add_column('product_variants', sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product_variants', sa.Column('dietary_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('product_variants', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('product_variants', sa.Column('availability_status', sa.String(length=50), nullable=False))
    op.add_column('product_variants', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('product_variants', sa.Column('purchase_count', sa.Integer(), nullable=True))
    op.create_index('idx_variants_availability', 'product_variants', ['availability_status'], unique=False)
    op.create_index('idx_variants_dietary_tags', 'product_variants', ['dietary_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_variants_specifications', 'product_variants', ['specifications'], unique=False, postgresql_using='gin')
    op.drop_index('idx_products_availability', table_name='products')
    op.drop_index('idx_products_price_range', table_name='products')
    op.drop_index('idx_products_specifications', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'min_price')
    op.drop_column('products', 'purchase_count')
    op.drop_column('products', 'dietary_tags')
    op.drop_column('products', 'max_price')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'availability_status')
    op.drop_column('products', 'view_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('availability_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('max_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('dietary_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('purchase_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('min_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('idx_products_specifications', 'products', ['specifications'], unique=False, postgresql_using='gin')
    op.create_index('idx_products_price_range', 'products', ['min_price', 'max_price'], unique=False)
    op.create_index('idx_products_availability', 'products', ['availability_status'], unique=False)
    op.drop_index('idx_variants_tags', table_name='product_variants', postgresql_using='gin')
    op.drop_index('idx_variants_specifications', table_name='product_variants', postgresql_using='gin')
    op.drop_index('idx_variants_dietary_tags', table_name='product_variants', postgresql_using='gin')
    op.drop_index('idx_variants_availability', table_name='product_variants')
    op.drop_column('product_variants', 'purchase_count')
    op.drop_column('product_variants', 'view_count')
    op.drop_column('product_variants', 'availability_status')
    op.drop_column('product_variants', 'tags')
    op.drop_column('product_variants', 'dietary_tags')
    op.drop_column('product_variants', 'specifications')
    op.drop_column('product_variants', 'max_price')
    op.drop_column('product_variants', 'min_price')
    # ### end Alembic commands ###
