"""Add blog categories, tags, and comments
Revision ID: 6475d58194b6
Revises: ca765f110fe1
Create Date: 2025-12-06 07:36:01.719922
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6475d58194b6'
down_revision: Union[str, Sequence[str], None] = 'ca765f110fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('blog_tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comments',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', postgresql.UUID(), nullable=False),
    sa.Column('blog_post_id', postgresql.UUID(), nullable=False),
    sa.Column('parent_id', postgresql.UUID(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_tags',
    sa.Column('blog_post_id', postgresql.UUID(), nullable=False),
    sa.Column('blog_tag_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['blog_tag_id'], ['blog_tags.id'], ),
    sa.PrimaryKeyConstraint('blog_post_id', 'blog_tag_id')
    )

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category_id', postgresql.UUID(), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seo_keywords', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_foreign_key(None, 'blog_categories', ['category_id'], ['id'])
        batch_op.drop_column('tags')
    
    # Populate slug for existing blog posts
    op.execute("UPDATE blog_posts SET slug = LOWER(REPLACE(title, ' ', '-')) WHERE slug IS NULL")
    
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)

    # Add comments relationship to users table (ORM-only, no DB change needed here)
    # No explicit DB migration for this relationship addition, it's handled at the ORM level.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('category_id')
        batch_op.drop_column('slug')

    op.drop_table('blog_post_tags')
    op.drop_table('comments')
    op.drop_table('blog_tags')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###